#!/bin/bash

# Curls a payload at boot to provide for netboot automation functions.
# /usr/local/bin/com.org.netboot
# http://localhost/netboot.zip

root_volume="$3"; if [ -z "${root_volume}" ] || [ "${root_volume}" = "/" ]; then root_volume=""; fi
operating_system=$(defaults read "${root_volume}/System/Library/CoreServices/SystemVersion" ProductVersion)

me=$0
directory=$(dirname ${me})
package_name=$(basename ${directory}) # com.org.netboot.RANDOM
daemon=$(echo ${package_name} | cut -d "." -f1-3) # com.org.netboot

sudo defaults write "${root_volume}/Library/LaunchDaemons/${daemon}" KeepAlive -bool TRUE
sudo defaults write "${root_volume}/Library/LaunchDaemons/${daemon}" Label "${daemon}"
sudo defaults write "${root_volume}/Library/LaunchDaemons/${daemon}" ProgramArguments -array "/bin/sh" "-c" "\"sleep 5; [ -e '/usr/local/bin/${daemon}' ] && sudo /usr/local/bin/${daemon} || exit 0\""
sudo defaults write "${root_volume}/Library/LaunchDaemons/${daemon}" RunAtLoad -bool TRUE
sudo defaults write "${root_volume}/Library/LaunchDaemons/${daemon}" StandardOutPath -string "/tmp/${daemon}.log"

sudo chown root:wheel "${root_volume}/Library/LaunchDaemons/${daemon}.plist"
sudo chmod 644 "${root_volume}/Library/LaunchDaemons/${daemon}.plist"

exit 0
