#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //
formatted_date=$(date +"%Y%m%d%H%M%S")

#
# disable Dockfixup
#
# the plist
mv "${path_root}/Library/Preferences/com.apple.dockfixup.plist" "${path_root}/Library/Preferences/com.apple.dockfixup.plist.${formatted_date}"
	
exit 0