#!/bin/bash

# Edit this to modify options
# /Volumes/Mac\ OS\ X\ Base\ System/System/Installation/CDIS/OS\ X\ Utilities.app/Contents/Resources/Utilities.plist

# Find it
recover_hd_volume=$(diskutil list | grep "Recovery HD" | awk '{print $7}')

# Mount it
diskutil mount "/dev/${recover_hd_volume}"

# Look in it
cd /Volumes/Recovery\ HD/com.apple.recovery.boot/

# Make a R/W BaseSystem.dmg copy
hdiutil convert -format UDRW -o ~/Desktop/temp.dmg /Volumes/Recovery\ HD/com.apple.recovery.boot/BaseSystem.dmg

# Mount R/W BaseSystem.dmg copy
hdiutil attach ~/Desktop/temp.dmg

# Mod it

# Un Mount it
diskutil unmount /Volumes/Mac\ OS\ X\ Base\ System/

# Un Mount Recovery HD
diskutil unmount "/dev/${recover_hd_volume}"

# Move the R BaseSystem.dmg
# You got a copy of the original right?
sudo rm -f /Volumes/Recovery\ HD/com.apple.recovery.boot/BaseSystem.dmg

# Copy the R/W version
sudo hdiutil convert -format UDZO -o /Volumes/Recovery\ HD/com.apple.recovery.boot/BaseSystem.dmg  ~/Desktop/temp.dmg