# This is just a template
# TODO
# Offer partitioning options or detect partition names for environments
# where you now what the name is going to be.
# Partition
# Install/Restore
# Bless?
# Reboot
# FINISH CODING HERE BELOW

export PS3='
   Restore a DMG/Install a PKG [1-9] or [q] to quit:'

clear

# lots of variables going on here, more thought required
# lets assume for now:
  # the person using this boot disk knows what they are doing!
  # only one dev is connected, ie. we are only concerned with /dev/disk0
  # the disk is either not partitioned "Macintosh HD"
    # or the disk is partitioned "System" and "Data"
    # if it is already partitioned it was done so using standards, ie. 50%/50% or min50gb/*
  #

function diskManage () {
  echo "Disks"
  diskutil list
  echo " "
  echo "Volumes"
  df -k | grep "/Volumes"
  echo " "
  echo -n "Looking for a DATA partition => "
  df -k | grep "/Volumes/Data"
  if [ $? -eq 0 ]; then
    echo "Found what looks to be a DATA partition."
    echo " "
    echo -n "Looking for a SYSTEM partition => "
    df -k | grep "/Volumes/System"
    if [ $? -eq 0 ]; then
      echo "Found what looks to be a SYSTEM partition."
      echo "Assuming the partition sizes are standard."
      ${1}
      exit
    else
      echo "Doesn't seem to be a DATA partition."
    fi
  else
    echo "Doesn't seem to be a DATA partition."
  fi

  # FINISH CODING HERE

  diskSize=$(diskutil info /Volumes/System | grep Total | awk '{print $5}' | sed s/\(//g)
  if [[ $(($diskSize / 1073741824)) -gt 100 ]]; then
    echo " "
    echo "disk larger thn 100gb, partition 50/50"
  else
    echo " "
    echo "disk less than 100gb, partition 50gb/*"
  fi
  #diskutil eraseVolume HFS+ Macintosh\ HD /Volumes/Macintosh\ HD
  #diskutil splitPartition /Volumes/Macintosh\ HD JHFS+ vol1 12g MS-DOS VOL2 8g JHFS+ vol3 0b
}

# Your function here
function asrRestore () {
  echo "installer -pkg ${fileName} -target /"
}

# Your function here
function osxInstall () {
  echo "sudo asr -restore -source ${fileName} -target / -erase -format HFS+ -noverify"
}

fileList=$(find /INSTALL -maxdepth 1 -type f | grep '.dmg\|.pkg' | sed s/\\/INSTALL//g | sed s/\\///g)
if [ $? -eq 0 ]; then
  echo "   O S X | E N T E R P R I S E"
  echo "   The following disk images and osx installers have been found."
  echo " "
else
  clear
fi
select fileName in $fileList; do
  	if [ -n "$fileName" ]; then
    	export InstallerFile="${fileName}"
  	fi
  	if [[ "${fileName}" == *.pkg ]]; then
  		diskManage osxInstall
    else
      clear
  	fi
  	if [[ "${fileName}" == *.dmg ]]; then
  	 diskManage asrRestore
    else
      clear
    fi
  break
done