#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //
device_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9 etc

#
# autlogin
#
# shortname
short_name="YOUR_LOGIN_USER_HERE"
# the plist
[[ ! -z "${short_name}" ]] && defaults write "${path_root}/Library/Preferences/com.apple.loginwindow.plist" autoLoginUser -string "${short_name}" || exit 1
[[ -e "${path_root}/Library/Preferences/com.apple.loginwindow.plist" ]] && chown root:wheel "${path_root}/Library/Preferences/com.apple.loginwindow.plist"  || exit 1
[[ -e "${path_root}/Library/Preferences/com.apple.loginwindow.plist" ]] && chmod 644 "${path_root}/Library/Preferences/com.apple.loginwindow.plist" || exit 1
[[ -e "${path_root}/Library/Preferences/com.apple.loginwindow.plist.lockfile" ]] && srm -f "${path_root}/Library/Preferences/com.apple.loginwindow.plist.lockfile"
# the payload
[[ -e "${path_root}/tmp/kcpassword.${device_os}" ]] && cp -f "${path_root}/tmp/kcpassword.${device_os}" "${path_root}/etc/kcpassword" || exit 1
[[ -e "${path_root}/etc/kcpassword" ]] && chown root:wheel "${path_root}/etc/kcpassword" || exit 1
[[ -e "${path_root}/etc/kcpassword" ]] && chmod 600 "${path_root}/etc/kcpassword" || exit 1
[[ -e "${path_root}/etc/kcpassword.disabled" ]] && srm -f "${path_root}/etc/kcpassword.disabled"

exit 0
