#!/bin/bash
#
# enable autlogin user
# ensure your payload (/tmp/auto_conf.plist) is configured with your autologin user SHORTNAME
#
path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //
dev_os=$(defaults read "${path_root}/System/Library/CoreServices/SystemVersion" ProductVersion)	# 10.9.x etc
short_name=$(defaults read "${path_root}/tmp/auto_conf.plist" autoLoginUser) # autoLoginUser string (shortname)
# preference
the_plist="${path_root}/Library/Preferences/com.apple.loginwindow.plist"
[[ ! -z "${short_name}" ]] && defaults write "${the_plist}" autoLoginUser -string "${short_name}" || exit 1
[[ -e "${the_plist}" ]] && chown root:wheel "${the_plist}"  || exit 1
[[ -e "${the_plist}" ]] && chmod 644 "${the_plist}" || exit 1
# payload
[[ -e "${path_root}/etc/kcpassword" ]] && mv -f "${path_root}/etc/kcpassword"{,."${formatted_date}"}
[[ -e "${path_root}/tmp/kcpassword.${dev_os}" ]] && cp -f "${path_root}/tmp/kcpassword.${dev_os}" "${path_root}/etc/kcpassword" || exit 1
[[ -e "${path_root}/etc/kcpassword" ]] && chown root:wheel "${path_root}/etc/kcpassword" || exit 1
[[ -e "${path_root}/etc/kcpassword" ]] && chmod 600 "${path_root}/etc/kcpassword" || exit 1
[[ -e "${path_root}/etc/kcpassword.disabled" ]] && srm -f "${path_root}/etc/kcpassword.disabled"
# maybe check if the payload worked, if it didn't remove the preference changes so this payload doesn't leave anything behind

exit 0
