#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

#
# the vnc password
#
vnc_pwd="YOUR_HASH_HERE"
echo "${vnc_pwd}" > "${path_root}/Library/Preferences/com.apple.VNCSettings.txt"
[[ -e "${path_root}/Library/Preferences/com.apple.VNCSettings.txt" ]] && chown -R root:wheel "${path_root}/Library/Preferences/com.apple.VNCSettings.txt"
[[ -e "${path_root}/Library/Preferences/com.apple.VNCSettings.txt" ]] && chmod -R 600 "${path_root}/Library/Preferences/com.apple.VNCSettings.txt"

#
# always new existing session control
#
defaults write "${path_root}/Library/Preferences/com.apple.RemoteManagement.plist" VNCAlwaysStartOnConsole -bool true

exit 0