#!/bin/bash
path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

defaults delete "${path_root}/System/Library/LaunchDaemons/com.apple.loginwindow.plist" ProgramArguments
defaults write "${path_root}/System/Library/LaunchDaemons/com.apple.loginwindow.plist" ProgramArguments -array-add "/var/firstboot/script"
sudo chown root:wheel "${path_root}/System/Library/LaunchDaemons/com.apple.loginwindow.plist"
sudo chmod 644 "${path_root}/System/Library/LaunchDaemons/com.apple.loginwindow.plist"

exit 0
