#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

#
# hide local admin users
# disable external accounts (i.e. accounts stored on drives other than the boot drive.)
# additional loginwindow system information
#
# the plist
the_plist="${path_root}/Library/Preferences/com.apple.loginwindow.plist"
defaults write "${the_plist}" Hide500Users -bool YES
defaults write "${the_plist}" EnableExternalAccounts -bool NO
defaults write "${the_plist}" AdminHostInfo "DSStatus"
[[ -e "${the_plist}" ]] && chown root:wheel "${the_plist}"
[[ -e "${the_plist}" ]] && chmod 644 "${the_plist}"
[[ -e "${the_plist}.lockfile" ]] && srm -f "${the_plist}.lockfile"

exit 0
