#!/bin/bash
#
# shortname in Connect to Server dialog
# just to keep it consistent for end users 
#
path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //
#
# the plist
the_plist="${path_root}/Library/Preferences/com.apple.NetworkAuthorization.plist"
[[ -e "${the_plist}" ]] && cp -f "${the_plist}"{,."${formatted_date}"}
defaults write "${the_plist}" UseDefaultName -bool NO
defaults write "${the_plist}" UseShortName -bool YES
[[ -e "${the_plist}" ]] && chown root:wheel "${the_plist}"
[[ -e "${the_plist}" ]] && chmod 644 "${the_plist}"

exit 0
