#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

vnc_pwd=$(defaults read "${path_root}/tmp/auto_conf.plist vnc_hash")
motd_banner=$(defaults read "${path_root}/tmp/auto_conf.plist motd_banner")

#
# ard agent always
#
# LaunchAgent that always configures Apple Remote Desktop client to require the end user to accept an incoming connection
#
the_agent="${path_root}/Library/LaunchAgents/com.org.ard.plist"
defaults write "${the_agent}" KeepAlive -bool FALSE
defaults write "${the_agent}" Label "com.org.ard"
defaults write "${the_agent}" ProgramArguments -array "/bin/sh" "-c" "/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate -configure -allowAccessFor -allUsers -access -on -privs -GenerateReports -ChangeSettings -SendFiles -TextMessages -DeleteFiles -clientopts -setvnclegacy -vnclegacy no -setreqperm -reqperm yes -setmenuextra -menuextra yes -restart -agent"
defaults write "${the_agent}" RunAtLoad -bool TRUE
# debug
#defaults write "${the_agent}" StandardErrorPath -string "/tmp/com.org.ard.stderr.log"
#defaults write "${the_agent}" StandardOutPath -string "/tmp/com.org.ard.stdout.log"
defaults write "${the_agent}" ThrottleInterval -int 900
[[ -e "${the_agent}" ]] && chown root:wheel "${the_agent}"
[[ -e "${the_agent}" ]] && chmod 644 "${the_agent}"

#
# ssh daemon always
#
# LaunchDaemon that always configures ssh access
#
the_daemon="${path_root}"
defaults write "${the_daemon}" KeepAlive -bool TRUE
defaults write "${the_daemon}" Label "com.org.ssh"
defaults write "${the_daemon}" ProgramArguments -array "/bin/sh" "-c" "\"sleep 10; systemsetup -setremotelogin on\""
defaults write "${the_daemon}" RunAtLoad -bool TRUE
# debug
# defaults write "${the_daemon}" StandardErrorPath -string "/tmp/com.org.ssh.stderr.log"
# defaults write "${the_daemon}" StandardOutPath -string "/tmp/com.org.ssh.stdout.log"
defaults write "${the_daemon}" ThrottleInterval -int 900
[[ -e "${the_daemon}" ]] && chown root:wheel "${the_daemon}"
[[ -e "${the_daemon}" ]] && chmod 644 "${the_daemon}"

#
# the motd banner
#
echo " " > "${path_root}/etc/motd"
echo "${motd_banner}" >> "${path_root}/etc/motd"
echo " " >> "${path_root}/etc/motd"

#
# the vnc password
#
the_vnc="${path_root}/Library/Preferences/com.apple.VNCSettings.txt"
echo "${vnc_pwd}" > "${the_vnc}"
[[ -e "${the_vnc}" ]] && chown -R root:wheel "${the_vnc}"
[[ -e "${the_vnc}" ]] && chmod -R 600 "${the_vnc}"

#
# always new existing session control
#
defaults write "${path_root}/Library/Preferences/com.apple.RemoteManagement.plist" VNCAlwaysStartOnConsole -bool true

exit 0
