#!/bin/bash

Heck, for fun I just created a 10TB (yes, 10 Terra Bytes) Ram Disk, without any problem.
~$ diskutil erasevolume HFS+ BIGDISK `hdiutil attach -nomount ram://20480000000`
Started erase on disk4
Unmounting disk
Erasing
Initialized /dev/rdisk4 as a 10 TB HFS Plus volume
Mounting disk
Finished erase on disk4 BIGDISK
~$ df -h /Volumes/BIGDISK/
Filesystem Size Used Avail Capacity Mounted on
/dev/disk4 9.5Ti 993Mi 9.5Ti 1% /Volumes/BIGDISK