#!/bin/bash

ROOT="$3"; if [ -z "${ROOT}" ] || [ "${ROOT}" = "/" ]; then ROOT=""; fi
OS=$(defaults read "${ROOT}/System/Library/CoreServices/SystemVersion" ProductVersion)
ME=$0

# Make it cleaner?
# sudo "${ROOT}/tmp/ccm/CMUninstall"
# sudo "${ROOT}/tmp/ccm/CMUninstall" -c

# Let ccmsetup do it?
#[ -e "${ROOT}/tmp/ccm/CMClient.pkg" ] && sudo installer -pkg "${ROOT}/tmp/ccm/CMClient.pkg" -target "${ROOT}/"

pushd "${ROOT}/tmp/ccm"
sudo "${ROOT}/tmp/ccm/ccmsetup"
sudo "${ROOT}/tmp/ccm/enroll"

exit 0