#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //
formatted_date=$(date +"%Y%m%d%H%M%S")

#
# Defaults
#
# the plist
# com.apple.airplay.plist
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.airplay.dock" showInMenuBarIfPresent -bool false
# com.apple.dashboard
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dashboard" layer-gadgets -array '<dict></dict>'
# com.apple.driver.AppleBluetoothMultitouch.trackpad
defaults write "${path_root}/Library/Preferences/.GlobalPreferences com.apple.mouse.tapBehavior.plist" -int 1
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad" Clicking -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad" Dragging -int 0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad" DragLock -int 0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad" TrackpadThreeFingerDrag -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.trackpad" Dragging -int 0
# com.apple.driver.AppleBluetoothMultitouch.mouse
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseButtonDivision -int 55
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseButtonMode -string TwoButton
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseButtonDivision -int 55
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseTwoFingerDoubleTapGesture -int 0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.driver.AppleBluetoothMultitouch.mouse" MouseTwoFingerHorizSwipeGesture -int 0
# com.apple.dock.plist (basic settings only).
#defaults write "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" autohide -bool false
#defaults write "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" launchanim -bool false
#defaults write "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" mineffect -string "scale"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" wvous-bl-corner -int 4
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" wvous-bl-modifier -int 0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" wvous-br-corner -int 5
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock" wvous-br-modifier -int 0
# com.apple.ATS.plist
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.ATS" ATSAutoActivation -string ATSAutoActivationDisable
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.ATS" ATSProtectRequiredSystemFontsSetting -string NO
# com.apple.Console.plist
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Console" ApplePersistenceIgnoreState YES
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Console" NSQuitAlwaysKeepsWindows -int 0
#com.apple.DiskUtility.plist
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.DiskUtility" advanced-image-options -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.DiskUtility" DUDebugMenuEnabled -bool true
# com.apple.finder.plist (possibly redundant if DisableAllAnimations is TRUE, requires testing).
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" AnimateInfoPanes -bool false
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" AnimateWindowZoom -bool false
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" DisableAllAnimations -bool true
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ZoomRects -bool false
# Just some standardisation
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" _FXShowPosixPathInTitle -bool true
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" DownloadsFolderListViewSettingsVersion -int 1
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" FXDefaultSearchScope -string SCcf
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" FXPreferredViewStyle -string Nlsv
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" NewWindowTarget -string PfHm
#defaults write "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ProhibitFinderPreferences -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" QLEnableTextSelection -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" RemoveIDiskFromSidebarOnStartup -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ShowHardDrivesOnDesktop -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ShowMountedServersOnDesktop -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ShowRemovableMediaOnDesktop -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ShowPathbar -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder" ShowStatusBar -bool true
# com.apple.FontBook.plist
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.FontBook" FBValidateFontsBeforeInstalling -bool false
# com.apple.helpviewer
#defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.helpviewer" DevMode -bool false
# iTunes
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disableCheckForUpdates -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disableGeniusSidebar -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disableGetAlbumArtwork -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disablePing -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disablePingSidebar -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disablePodcasts -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disableRadio -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" disableSharedMusic -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" dontAutomaticallySyncIPods -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.iTunes" lookForSharedMusic -bool false
# Mail
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.mail" DisableInlineAttachmentViewing -bool true
# NetworkBrowser
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.NetworkBrowser" DisableAirDrop -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.NetworkBrowser" BrowseAllInterfaces -bool false
# Printing Prefs
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.print.PrintingPrefs" "Quit When Finished" -bool true
# Safari
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" ApplePersistenceIgnoreState YES
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" AutoFillFromAddressBook -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" AutoFillMiscellaneousForms -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" AutoFillPasswords -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" DomainsToNeverSetUp -array "aol.com" "facebook.com" "flickr.com" "google.com" "twitter.com" "vimeo.com" "yahoo.com"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" IncludeDebugMenu 1
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" LastDisplayedWelcomePageVersionString -string 4.0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" NewWindowBehaviour 0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" NSQuitAlwaysKeepsWindows -int 0
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" RestoreSessionAtLaunch -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" WebKitJavaScriptCanOpenWindowsAutomatically -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" ShowStatusBar -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.Safari" HomePage "http://intranet"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.internetconfigpriv" WWWHomePage "http://intranet"
# System Preferences Pane
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systempreferences" com.apple.dtandsspref.lastselectedtab "com.apple.preference.desktopscreeneffect.screeneffects"
# Menu Extras
defaults delete "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras" -array-add -string "/Applications/Utilities/Keychain Access.app/Contents/Resources/Keychain.menu"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras" -array-add -string "/System/Library/CoreServices/Menu Extras/Bluetooth.menu"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras" -array-add -string "/System/Library/CoreServices/Menu Extras/TextInput.menu"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras" -array-add -string "/System/Library/CoreServices/Menu Extras/Volume.menu"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras" -array-add -string "/System/Library/CoreServices/Menu Extras/Displays.menu"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.systemuiserver" "menuExtras" -array-add -string "/System/Library/CoreServices/Menu Extras/RemoteDesktop.menu"
# TimeMachine
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.TimeMachine" DoNotOfferNewDisksForBackup -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.TimeMachine" AutoBackup -bool false
# Trackpad
defaults -currentHost write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/ByHost/.GlobalPreferences" "com.apple.mouse.tapBehavior" -int 1
# com.apple.universalaccess.plist
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.universalaccess" voiceOverOnOffKey -bool false
# com.apple.CrashReporter.plist (hide from scared end users. maybe switch to basic mode...offers them the choice to delete prefs after second crash).
#defaults write "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.CrashReporter" DialogType Server
# com.apple.desktopservices.plist (not doing this anymore. Causes weird behaviour with Windows Shares in pre 10.7).
#defaults write "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.desktopservices" DSDontWriteNetworkStores -bool TRUE
# Speed up finder info on remote volumes?
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded:Comments bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:Comments NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded:General bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:General YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded:MetaData bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:MetaData NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded:Name bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:Name NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded:Preview bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:Preview NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :FXInfoPanesExpanded:Privileges bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :FXInfoPanesExpanded:Privileges NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
# set standard views, remove previews etc to speed up finder (also to avoid WiFs bug)
#if [ "${device_os}" == "10.7.5" ]; then
# echo "10.7.5 so skipping finder, should probably do this with 10.8 too because do we really need this?"
#else
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:ArrangeBy string dnam" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:ArrangeBy dnam" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:ColumnShowFolderArrow bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:ColumnShowFolderArrow YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:ColumnShowIcons bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:ColumnShowIcons NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:ColumnWidth integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:ColumnWidth 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:FontSize integer 12" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:FontSize 12" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:PreviewDisclosureState bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:PreviewDisclosureState YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:SharedArrangeBy string kipl" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:SharedArrangeBy kipl" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:ShowIconThumbnails bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:ShowIconThumbnails NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewOptions:ColumnViewOptions:ShowPreview bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewOptions:ColumnViewOptions:ShowPreview YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:IconViewSettings dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:IconViewSettings:arrangeBy string none" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy none" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:IconViewSettings:showIconPreview bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showIconPreview NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:calculateAllSizes bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:calculateAllSizes NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:iconSize integer 16" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:iconSize 16" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:scrollPositionX integer 0" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:scrollPositionX 0" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:scrollPositionY integer 0" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:scrollPositionY 0" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:showIconPreview bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:showIconPreview NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:sortColumn string name" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:sortColumn name" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:textSize integer 12" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:textSize 12" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:useRelativeDates bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:useRelativeDates NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:viewOptionsVersion integer 1" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:viewOptionsVersion 1" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:name dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:name:ascending bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:name:ascending YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:name:index integer 0" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:name:index 0" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:name:visible bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:name:visible YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:name:width integer 300" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:name:width 300" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateCreated dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateCreated:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateCreated:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateCreated:index integer 1" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateCreated:index 1" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateCreated:visible bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateCreated:visible YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateCreated:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateCreated:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateModified dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateModified:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateModified:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateModified:index integer 2" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateModified:index 2" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateModified:visible bool YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateModified:visible YES" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateModified:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateModified:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateLastOpened dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateLastOpened:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateLastOpened:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateLastOpened:index integer 3" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateLastOpened:index 3" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateLastOpened:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateLastOpened:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateLastOpened:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateLastOpened:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateAdded dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateAdded:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateAdded:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateAdded:index integer 4" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateAdded:index 4" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateAdded:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateAdded:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:dateAdded:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:dateAdded:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:comments dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:comments:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:comments:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:comments:index integer 5" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:comments:index 5" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:comments:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:comments:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:comments:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:comments:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:kind dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:kind:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:kind:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:kind:index integer 6" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:kind:index 6" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:kind:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:kind:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:kind:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:kind:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:label dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:label:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:label:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:label:index integer 7" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:label:index 7" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:label:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:label:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:label:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:label:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:size dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:size:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:size:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:size:index integer 8" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:size:index 8" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:size:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:size:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:size:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:size:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:version dict" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:version:ascending bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:version:ascending NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:version:index integer 9" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:version:index 9" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:version:visible bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:version:visible NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Add :StandardViewSettings:ListViewSettings:columns:version:width integer 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#/usr/libexec/PlistBuddy -c "Set :StandardViewSettings:ListViewSettings:columns:version:width 200" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.finder.plist"
#fi
# com.apple.symbolichotkeys.plist (Disable Dashboard and Mission Control Keys so they are default Fn keys), arrggg! changes every time the OS adds functionality or new keys. Find and disable 10.8 dictation key.
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:32:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:32:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:33:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:33:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:34:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:34:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:35:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:35:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:36:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:36:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:37:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:37:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:52:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:52:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:59:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:59:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:62:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:62:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:63:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:63:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:64:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:64:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:65:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:65:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Add :AppleSymbolicHotKeys:73:enabled bool NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"
#/usr/libexec/PlistBuddy -c "Set :AppleSymbolicHotKeys:73:enabled NO" "/System/Library/User Template/English.lproj/Library/Preferences/com.apple.symbolichotkeys.plist"


# .GlobalPreferences
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" AppleKeyboardUIMode -int 2
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" AppleMiniaturizeOnDoubleClick -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" AppleShowAllExtensions -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" AppleShowScrollBars -string "Always"
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" NSAutomaticSpellingCorrectionEnabled -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" NSAutomaticWindowAnimationsEnabled -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" NSDocumentSaveNewDocumentsToCloud -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" NSNavPanelExpandedStateForSaveMode -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" NSQuitAlwaysKeepsWindows -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" PMPrintingExpandedStateForPrint -bool true
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" com.apple.swipescrolldirection -bool false
defaults write "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/.GlobalPreferences" com.apple.keyboard.fnState -bool true


# com.apple.dock.plist (lazy way for now)
cat > "${path_root}/System/Library/User Template/English.lproj/Library/Preferences/com.apple.dock.plist" << EOPROFILE
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>autohide</key>
	<false/>
	<key>launchanim</key>
	<false/>
	<key>mineffect</key>
	<string>scale</string>
	<key>mod-count</key>
	<integer>6</integer>
	<key>persistent-apps</key>
	<array>
		<dict>
			<key>GUID</key>
			<integer>2837871025</integer>
			<key>tile-data</key>
			<dict>
				<key>bundle-identifier</key>
				<string>com.apple.launchpad.launcher</string>
				<key>dock-extra</key>
				<false/>
				<key>file-data</key>
				<dict>
					<key>_CFURLAliasData</key>
					<data>
					AAAAAACoAAMAAQAAzpITwgAASCsAAAAAAAAA
					SwACF24AAM4/EF8AAAAACSD//gAAAAAAAAAA
					/////wABAAQAAABLAA4AHAANAEwAYQB1AG4A
					YwBoAHAAYQBkAC4AYQBwAHAADwAaAAwATQBh
					AGMAaQBuAHQAbwBzAGgAIABIAEQAEgAaQXBw
					bGljYXRpb25zL0xhdW5jaHBhZC5hcHAAEwAB
					LwD//wAA
					</data>
					<key>_CFURLString</key>
					<string>file:///Applications/Launchpad.app/</string>
					<key>_CFURLStringType</key>
					<integer>15</integer>
				</dict>
				<key>file-label</key>
				<string>Launchpad</string>
				<key>file-mod-date</key>
				<integer>3460239455</integer>
				<key>file-type</key>
				<integer>169</integer>
				<key>parent-mod-date</key>
				<integer>3465680967</integer>
			</dict>
			<key>tile-type</key>
			<string>file-tile</string>
		</dict>
		<dict>
			<key>GUID</key>
			<integer>2837871044</integer>
			<key>tile-data</key>
			<dict>
				<key>bundle-identifier</key>
				<string>com.apple.exposelauncher</string>
				<key>dock-extra</key>
				<false/>
				<key>file-data</key>
				<dict>
					<key>_CFURLAliasData</key>
					<data>
					AAAAAAC6AAMAAQAAzpITwgAASCsAAAAAAAAA
					SwACF3kAAM4/EJAAAAAACSD//gAAAAAAAAAA
					/////wABAAQAAABLAA4AKAATAE0AaQBzAHMA
					aQBvAG4AIABDAG8AbgB0AHIAbwBsAC4AYQBw
					AHAADwAaAAwATQBhAGMAaQBuAHQAbwBzAGgA
					IABIAEQAEgAgQXBwbGljYXRpb25zL01pc3Np
					b24gQ29udHJvbC5hcHAAEwABLwD//wAA
					</data>
					<key>_CFURLString</key>
					<string>file:///Applications/Mission%20Control.app/</string>
					<key>_CFURLStringType</key>
					<integer>15</integer>
				</dict>
				<key>file-label</key>
				<string>Mission Control</string>
				<key>file-mod-date</key>
				<integer>3460239504</integer>
				<key>file-type</key>
				<integer>169</integer>
				<key>parent-mod-date</key>
				<integer>3465680967</integer>
			</dict>
			<key>tile-type</key>
			<string>file-tile</string>
		</dict>
	</array>
	<key>persistent-others</key>
	<array/>
	<key>version</key>
	<integer>1</integer>
</dict>
</plist>
EOPROFILE

exit 0
