#!/bin/bash

path_root="$3"; if [ -z "${path_root}" ] || [ "${path_root}" = "/" ]; then path_root=""; fi # fix //

#
# hide local admin users
# disable external accounts (i.e. accounts stored on drives other than the boot drive.)
# additional loginwindow system information
#
# the plist
defaults write "${path_root}/Library/Preferences/com.apple.loginwindow.plist" Hide500Users -bool YES
defaults write "${path_root}/Library/Preferences/com.apple.loginwindow.plist" EnableExternalAccounts -bool NO
defaults write "${path_root}/Library/Preferences/com.apple.loginwindow.plist" AdminHostInfo "DSStatus"

[[ -e "${path_root}/Library/Preferences/com.apple.loginwindow.plist" ]] && chown root:wheel "${path_root}/Library/Preferences/com.apple.loginwindow.plist"
[[ -e "${path_root}/Library/Preferences/com.apple.loginwindow.plist" ]] && chmod 644 "${path_root}/Library/Preferences/com.apple.loginwindow.plist"
[[ -e "${path_root}/Library/Preferences/com.apple.loginwindow.plist.lockfile" ]] && srm -f "${path_root}/Library/Preferences/com.apple.loginwindow.plist.lockfile"

exit 0